binary_sensor: !include_dir_list ../entities/knx/binary_sensors
button: !include_dir_list ../entities/knx/buttons
cover: !include_dir_list ../entities/knx/covers
climate: !include_dir_list ../entities/knx/climate
fan: !include_dir_list ../entities/knx/fans
light: !include_dir_list ../entities/knx/lights
notify: !include_dir_list ../entities/knx/notifies
number: !include_dir_list ../entities/knx/numbers
scene: !include_dir_list ../entities/knx/scences
sensor: !include_dir_list ../entities/knx/sensors
switch: !include_dir_list ../entities/knx/switches
weather: !include_dir_list ../entities/knx/weather