
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 24
  unit_system: metric
  currency: EUR
  time_zone: "Europe/Berlin"
  
api:

knx: !include integrations/knx.yaml
mqtt: !include integrations/mqtt.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  resources:
  - url: /local/hass-shutter-card.js
    type: module
  - url: /local/shutter-row.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.4.4
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.11.0
    type: module
    
# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram-api-key
    allowed_chat_ids:
      - !secret telegram-chat-id
      - !secret telegram-group-chat-id

# Example configuration.yaml entry for the notifier
notify:
  - platform: telegram
    name: telegram_smarthome
    chat_id: !secret telegram-chat-id
  - platform: telegram
    name: telegram_family
    chat_id: !secret telegram-group-chat-id

# todo 
sensor:
  - platform: edl21
    serial_port: /dev/serial/by-id/usb-Silicon_Labs_USB-IR-Kopf_001DDE3A-if00-port0
  - platform: command_line
    name: RPi CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    value_template: "{{ value | multiply(0.001) | round(2) }}"
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

template:
  - sensor:
    - name: 'Harmony Remote'
      state: >
        {{ state_attr('remote.wohnzimmer', 'current_activity') }}